### ISSUE TITLE
IMAGE GENERATION.

### ISSUE THREAD

**Issue by Lotfullah21** [MIT-Emerging-Talent/2024-group-05-08-cdsp#90]
![Correlation_Heatmap_GDP](https://github.com/MIT-Emerging-Talent/2024-group-05-08-cdsp/assets/85621380/6669ef67-8b9f-4da9-9e1e-e53f810d7f56)

**Comment by TasabeehAhmed** [comment]
Where you attempting to try something here? @Lotfullah21

**Comment by Lotfullah21** [comment]
Hello @TasabeehAhmed , I couldn't get you.

**Comment by TasabeehAhmed** [comment]
You opened this issue yesterday, is it by mistake? @Lotfullah21

**Comment by Lotfullah21** [comment]
NO, I was trying to generate the links for finding readme.
